chore: #40 Set Dependabot strategy to 'increse'
jfgreffier/playwright-relative-selector pull request #41
Opened 2020-11-28 18:04 UTC by yyvess

Update version semantic to patch

2020-11-28 20:59 UTC, jfgreffier requested changes

2020-11-28 20:59 UTC, jfgreffier commented on package.json
> +    "playwright": "~1.6.2",
Can you set it to `~1.4.2`, do a npm install and commit the package-lock.json ? In this way, we can verify that dependabot performs the update on next run

2020-11-28 20:59 UTC, jfgreffier commented on .gitignore
> +*.iml
Minor : check if you set up editorconfig support; it's a plugin in intellij if I remember. According to `.editorconfig`, files end with a newline

2020-11-29 00:48 UTC, yyvess reviewed
I update it

2020-11-29 00:48 UTC, yyvess commented on package.json
> +    "playwright": "~1.6.2",
I was tested it my fork it's look good =>
![image](https://user-images.githubusercontent.com/5787779/100527021-dd414b80-31ce-11eb-98d2-c09935351723.png)
PS: I change the default branch and force to run Dependabot manually to test it

2020-11-30 07:25 UTC, merged